### ISSUE TITLE
[Feature Request] Leave FFA

### ISSUE THREAD

**Issue by couleurm** [AndyRusso/pvplegacyutils#3]
Add a way to leave the FFA when you're already down there, e.g automatically relogging

**Comment by AndyRusso** [comment]
Hello.
Automatically relogging doesn't work since it puts the player back in FFA. So the only other way to do this is executing `/spawn` and then `/hub`.
`/spawn` takes 7 seconds before teleporting, so I don't see a rationale in automatic execution of `/hub` after teleporting - type it in the meantime.
I also asked a few FFA players and none of them had any need for this, so I don't see any reason to implement this.

If you'd like to PR this (don't worry if you don't), the way I see it could be done is a `/hub-force` (or suggest a better name!) which would do what I kinda described above.
I think a command is the best way to do it since it can interoperate with other mods like [Command Macros](https://modrinth.com/mod/command-macros).
You'd need to see if the player is in FFA too, check out the [`PvPLegacyUtilsAPI`](https://github.com/AndyRusso/pvplegacyutils/blob/40249b793bfaabcf0bf08a954fe6c684948bb038/src/main/java/io/github/andyrusso/pvplegacyutils/api/PvPLegacyUtilsAPI.java#L75) for that.
I'd prefer if the command didn't show in other locations, but if that's not reasonably/technologically possible I'd be fine with it regardless.

Contributing is optional, of course. For now, I'm closing this as not planned. Feel free to ask any further questions.
